//HintName: SortOrder_ModelBinder.g.cs
/// <auto-generated />

using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

/// <summary>
/// Generated by <see cref="EnumExt.ModelBinderAttribute"/> for <see cref="SortOrder"/> enum.
/// </summary>
public class SortOrderModelBinder : IModelBinder
{
    public Task BindModelAsync(ModelBindingContext bindingContext)
    {
        if (bindingContext == null)
        {
            throw new ArgumentNullException(nameof(bindingContext));
        }

        var valueProviderResult = bindingContext.ValueProvider.GetValue(bindingContext.ModelName);
        if (valueProviderResult == ValueProviderResult.None)
        {
            return Task.CompletedTask;
        }

        bindingContext.ModelState.SetModelValue(bindingContext.ModelName, valueProviderResult);
        var value = valueProviderResult.FirstValue;
        if (string.IsNullOrEmpty(value))
        {
            return Task.CompletedTask;
        }

        if (System.Enum.TryParse(typeof(SortOrder), value, true, out var result))
        {
            bindingContext.Result = ModelBindingResult.Success(result);
        }
        else
        {
            bindingContext.ModelState.TryAddModelError(bindingContext.ModelName, $"Value '{value}' is not valid for enum type {nameof(SortOrder)}.");
        }

        return Task.CompletedTask;
    }
}
