//HintName: SortOrder_ModelBinderAttribute.g.cs
/// <auto-generated />

using Microsoft.AspNetCore.Mvc;

/// <summary>
/// Generated by <see cref="EnumExt.ModelBinderAttribute"/> for <see cref="SortOrder"/> enum.
/// </summary>
public class SortOrderModelBinderAttribute : ModelBinderAttribute
{
    public SortOrderModelBinderAttribute()
    {
        BinderType = typeof(SortOrderModelBinder);
    }
}
