//HintName: ModelBinderAttribute.g.cs
/// <auto-generated />

namespace EnumExt
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Enum, Inherited = true, AllowMultiple = true)]
    internal sealed class ModelBinderAttribute : global::System.Attribute
    {
        internal ModelBinderAttribute()
        {
        }
    }
}
