//HintName: SortOrder_ArrayModelBinder.g.cs
/// <auto-generated />

using Microsoft.AspNetCore.Mvc.ModelBinding;
using System;
using System.Linq;

/// <summary>
/// Generated by <see cref="EnumExt.ModelBinderAttribute"/> for <see cref="SortOrder[]"/> enum.
/// </summary>
public class SortOrderArrayModelBinder : IModelBinder
{
    public Task BindModelAsync(ModelBindingContext bindingContext)
    {
        if (bindingContext == null)
        {
            throw new ArgumentNullException(nameof(bindingContext));
        }

        var valueProviderResult = bindingContext.ValueProvider.GetValue(bindingContext.ModelName);
        if (valueProviderResult == ValueProviderResult.None)
        {
            return Task.CompletedTask;
        }

        bindingContext.ModelState.SetModelValue(bindingContext.ModelName, valueProviderResult);
        var value = valueProviderResult.FirstValue;
        if (string.IsNullOrEmpty(value))
        {
            return Task.CompletedTask;
        }

        var values = value.Split(',', StringSplitOptions.RemoveEmptyEntries)
            .Select(v => v.Trim())
            .ToArray();

        var resultList = new System.Collections.Generic.List<SortOrder>();
        bool hasError = false;
        foreach (var item in values)
        {
            if (System.Enum.TryParse(typeof(SortOrder), item, true, out var parsed))
            {
                resultList.Add((SortOrder)parsed);
            }
            else
            {
                bindingContext.ModelState.TryAddModelError(bindingContext.ModelName, $"Value '{item}' is not valid for enum type {nameof(SortOrder)}.");
                hasError = true;
            }
        }

        if (!hasError)
        {
            bindingContext.Result = ModelBindingResult.Success(resultList.ToArray());
        }

        return Task.CompletedTask;
    }
}
