//HintName: SortOrder_ArrayModelBinderAttribute.g.cs
/// <auto-generated />

using Microsoft.AspNetCore.Mvc;

/// <summary>
/// Generated by <see cref="EnumExt.ModelBinderAttribute"/> for <see cref="SortOrder[]"/> enum.
/// </summary>
public class SortOrderArrayModelBinderAttribute : ModelBinderAttribute
{
    public SortOrderArrayModelBinderAttribute()
    {
        BinderType = typeof(SortOrderArrayModelBinder);
    }
}
