//HintName: JsonConverterAttribute.g.cs
/// <auto-generated />

namespace EnumExt
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("EnumExt", "1.6.0.0")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Enum, Inherited = true, AllowMultiple = true)]
    internal sealed class JsonConverterAttribute : global::System.Attribute
    {
        private EnumExt.JsonConverterLibrary _type;
        private EnumExt.ConversionStrategy _conversion;

        internal JsonConverterAttribute(EnumExt.JsonConverterLibrary type, EnumExt.ConversionStrategy conversion)
        {
            _type = type;
            _conversion = conversion;
        }
    }
}
