//HintName: Status_JsonConverter_Name.g.cs
/// <auto-generated />

using System.Text.Json;
using System.Text.Json.Serialization;

/// <summary>
/// Generated by <see cref="EnumExt.JsonConverterAttribute"/> for <see cref="Status"/> enum.
/// </summary>
public class StatusJsonConverterName : JsonConverter<Status>
{
    public override Status Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        return StatusExt.FromString(reader.GetString() ?? "");
    }

    public override void Write(Utf8JsonWriter writer, Status value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value.Name());
    }
}
