//HintName: ValueArrayConverterAttribute.g.cs
/// <auto-generated />

namespace EnumExt
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Enum, Inherited = true, AllowMultiple = true)]
    internal sealed class ValueArrayConverterAttribute : global::System.Attribute
    {
        private EnumExt.ConversionStrategy _conversion;

        internal ValueArrayConverterAttribute(EnumExt.ConversionStrategy conversion)
        {
            _conversion = conversion;
        }
    }
}
