//HintName: EnumExtensionsAttribute.g.cs
/// <auto-generated />

namespace EnumExt
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Enum, Inherited = true, AllowMultiple = true)]
    internal sealed class EnumExtensionsAttribute : global::System.Attribute
    {
        internal EnumExtensionsAttribute()
        {
        }
    }
}
