//HintName: Tag_ValueArrayConverter_SnakeCase.g.cs
/// <auto-generated />

using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

/// <summary>
/// Generated by <see cref="EnumExt.ValueArrayConverterAttribute"/> for <see cref="Tag"/> enum.
/// </summary>
public class TagValueArrayConverterSnakeCase() : ValueConverter<Tag[], string[]>(
    v => v.Select(e => e.SnakeCaseName()).ToArray(),
    v => v.Select(TagExt.FromSnakeCaseString).ToArray());
