//HintName: Priority_ValueConverterName.g.cs
/// <auto-generated />

using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

/// <summary>
/// Generated by <see cref="EnumExt.ValueConverterAttribute"/> for <see cref="Priority"/> enum.
/// </summary>
public class PriorityValueConverterName() : ValueConverter<Priority, string>(v => v.Name(), v => PriorityExt.FromString(v));
