//HintName: WrapperForState.g.cs
/// <auto-generated />

/// <summary>
/// Generated by <see cref="EnumExt.EnumTypeForAttribute"/> for <see cref="State"/> enum.
/// </summary>
[System.Serializable]
public class WrapperForState
{
    [UnityEngine.SerializeField] private Wrapper Idle;
    [UnityEngine.SerializeField] private Wrapper Running;

    public Wrapper GetIdle => Idle;
    public Wrapper GetRunning => Running;

    public WrapperForState() { }

    public WrapperForState(Wrapper idle, Wrapper running)
    {
        this.Idle = idle;
        this.Running = running;
    }

    public Wrapper Get(State key)
    {
        return key switch
        {
            State.Idle => Idle,
            State.Running => Running,
            _ => throw new System.ArgumentOutOfRangeException(nameof(key), key, null),
        };
    }

    public void Set(State key, Wrapper value)
    {
        switch (key)
        {
            case State.Idle: Idle = value; break;
            case State.Running: Running = value; break;
            default: throw new System.ArgumentOutOfRangeException(nameof(key), key, null);
        }
    }

    public void Apply(State key, System.Func<Wrapper, Wrapper> func)
    {
        switch (key)
        {
            case State.Idle: Idle = func(Idle); break;
            case State.Running: Running = func(Running); break;
            default: throw new System.ArgumentOutOfRangeException(nameof(key), key, null);
        }
    }

    public Wrapper[] Values => new[]
    {
        Idle,
        Running,
    };

    public System.Collections.Generic.Dictionary<State, Wrapper>  Dict => new System.Collections.Generic.Dictionary<State, Wrapper>()
    {
        { State.Idle, Idle },
        { State.Running, Running },
    };
}
