//HintName: CustomName.g.cs
/// <auto-generated />

/// <summary>
/// Generated by <see cref="EnumExt.EnumTypeForAttribute"/> for <see cref="ColorTest"/> enum.
/// </summary>
[System.Serializable]
public class CustomName
{
    [UnityEngine.SerializeField] private ClassWithString Red;
    [UnityEngine.SerializeField] private ClassWithString Blue;
    [UnityEngine.SerializeField] private ClassWithString Green;

    public ClassWithString GetRed => Red;
    public ClassWithString GetBlue => Blue;
    public ClassWithString GetGreen => Green;

    public CustomName() { }

    public CustomName(ClassWithString red, ClassWithString blue, ClassWithString green)
    {
        this.Red = red;
        this.Blue = blue;
        this.Green = green;
    }

    public ClassWithString Get(ColorTest key)
    {
        return key switch
        {
            ColorTest.Red => Red,
            ColorTest.Blue => Blue,
            ColorTest.Green => Green,
            _ => throw new System.ArgumentOutOfRangeException(nameof(key), key, null),
        };
    }

    public void Set(ColorTest key, ClassWithString value)
    {
        switch (key)
        {
            case ColorTest.Red: Red = value; break;
            case ColorTest.Blue: Blue = value; break;
            case ColorTest.Green: Green = value; break;
            default: throw new System.ArgumentOutOfRangeException(nameof(key), key, null);
        }
    }

    public void Apply(ColorTest key, System.Func<ClassWithString, ClassWithString> func)
    {
        switch (key)
        {
            case ColorTest.Red: Red = func(Red); break;
            case ColorTest.Blue: Blue = func(Blue); break;
            case ColorTest.Green: Green = func(Green); break;
            default: throw new System.ArgumentOutOfRangeException(nameof(key), key, null);
        }
    }

    public ClassWithString[] Values => new[]
    {
        Red,
        Blue,
        Green,
    };

    public System.Collections.Generic.Dictionary<ColorTest, ClassWithString>  Dict => new System.Collections.Generic.Dictionary<ColorTest, ClassWithString>()
    {
        { ColorTest.Red, Red },
        { ColorTest.Blue, Blue },
        { ColorTest.Green, Green },
    };
}
