//HintName: EnumTypeForAttribute.g.cs
/// <auto-generated />

namespace EnumExt
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("EnumExt", "1.4.0.0")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Enum, Inherited = true, AllowMultiple = true)]
    internal sealed class EnumTypeForAttribute : global::System.Attribute
    {
        private System.Type _type;
        private string _customName;
        private bool _unitySerializable;

        internal EnumTypeForAttribute(System.Type type, string customName = null, bool unitySerializable = true)
        {
            _type = type;
            _customName = customName;
            _unitySerializable = unitySerializable;
        }
    }
}
