//HintName: ClassWithT_List_IntForColorTest.g.cs
/// <auto-generated />

/// <summary>
/// Generated by <see cref="EnumExt.EnumTypeForAttribute"/> for <see cref="ColorTest"/> enum.
/// </summary>
[System.Serializable]
public class ClassWithT_List_IntForColorTest
{
    [UnityEngine.SerializeField] private ClassWithT<List<Int>> Red;
    [UnityEngine.SerializeField] private ClassWithT<List<Int>> Blue;
    [UnityEngine.SerializeField] private ClassWithT<List<Int>> Green;

    public ClassWithT<List<Int>> GetRed => Red;
    public ClassWithT<List<Int>> GetBlue => Blue;
    public ClassWithT<List<Int>> GetGreen => Green;

    public ClassWithT_List_IntForColorTest() { }

    public ClassWithT_List_IntForColorTest(ClassWithT<List<Int>> red, ClassWithT<List<Int>> blue, ClassWithT<List<Int>> green)
    {
        this.Red = red;
        this.Blue = blue;
        this.Green = green;
    }

    public ClassWithT<List<Int>> Get(ColorTest key)
    {
        return key switch
        {
            ColorTest.Red => Red,
            ColorTest.Blue => Blue,
            ColorTest.Green => Green,
            _ => throw new System.ArgumentOutOfRangeException(nameof(key), key, null),
        };
    }

    public void Set(ColorTest key, ClassWithT<List<Int>> value)
    {
        switch (key)
        {
            case ColorTest.Red: Red = value; break;
            case ColorTest.Blue: Blue = value; break;
            case ColorTest.Green: Green = value; break;
            default: throw new System.ArgumentOutOfRangeException(nameof(key), key, null);
        }
    }

    public void Apply(ColorTest key, System.Func<ClassWithT<List<Int>>, ClassWithT<List<Int>>> func)
    {
        switch (key)
        {
            case ColorTest.Red: Red = func(Red); break;
            case ColorTest.Blue: Blue = func(Blue); break;
            case ColorTest.Green: Green = func(Green); break;
            default: throw new System.ArgumentOutOfRangeException(nameof(key), key, null);
        }
    }

    public ClassWithT<List<Int>>[] Values => new[]
    {
        Red,
        Blue,
        Green,
    };

    public System.Collections.Generic.Dictionary<ColorTest, ClassWithT<List<Int>>>  Dict => new System.Collections.Generic.Dictionary<ColorTest, ClassWithT<List<Int>>>()
    {
        { ColorTest.Red, Red },
        { ColorTest.Blue, Blue },
        { ColorTest.Green, Green },
    };
}
