//HintName: Color_ValueList.g.cs
/// <auto-generated />

/// <summary>
/// Generated by <see cref="EnumExt.EnumValuesListAttribute"/> for <see cref="Color"/> enum.
/// </summary>
public static partial class ColorExt
{
    public static Color[] Values =
    {
        Color.Red,
        Color.Green,
        Color.Blue,
    };
}
