//HintName: EnumValuesListAttribute.g.cs
/// <auto-generated />

namespace EnumExt
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Enum, Inherited = true, AllowMultiple = true)]
    internal sealed class EnumValuesListAttribute : global::System.Attribute
    {
        internal EnumValuesListAttribute()
        {
        }
    }
}
