#nullable enable
using System;
using System.Linq;
using SourceGeneration.Utils.CodeBuilder;

namespace SourceGeneration.Utils.Common; 

public static class Utils
{
    public static string GeneratedCodeAttribute(this Type type)
    {
        var assemblyName = type.Assembly.GetName();
        return $"""[global::System.CodeDom.Compiler.GeneratedCodeAttribute("{assemblyName.Name}", "{assemblyName.Version}")]""";
    }

    public static string SimpleAttribute(string name, AttributeTargets target, bool allowMultiple = true)
    {
        return Attribute(name, null, target, allowMultiple, []);
    }
    
    public static string SimpleAttribute(string name, Type type, AttributeTargets target, bool allowMultiple = true)
    {
        return Attribute(name, type, target, allowMultiple, []);
    }
    
    public static string Attribute(
        string name, Type? type, AttributeTargets target, bool allowMultiple, (string type, string name, string? @default)[] fields
    )
    {
        var builder = new CodeBuilder.CodeBuilder();

        builder.AppendLineWithIdent("/// <auto-generated />");
        builder.AppendLine();
        
        using (new NamespaceBlock(builder, "EnumExt"))
        {
            if (type != null)
            {
                builder.AppendLineWithIdent(type.GeneratedCodeAttribute());
            }

            builder.AppendIdent().Append("[global::System.AttributeUsage(global::System.AttributeTargets.")
                .Append(target.ToString()).Append(", Inherited = true, AllowMultiple = ")
                .Append(allowMultiple ? "true" : "false").Append(")]").AppendLine();

            builder.AppendIdent().Append("internal sealed class ").Append(name.WithAttributePostfix())
                .Append(" : global::System.Attribute").AppendLine();

            using (new BracketsBlock(builder))
            {
                foreach (var f in fields)
                {
                    builder.AppendIdent().Append("private ").Append(f.type).Append(" _").Append(f.name).Append(";")
                        .AppendLine();
                }
                
                if (fields.Length > 0)
                {
                    builder.AppendLine();
                }
                
                builder.AppendIdent().Append("internal ").Append(name.WithAttributePostfix()).Append("(");
                builder.AppendArray(fields, (f, b) =>
                {
                    b.Append(f.type).Append(" ").Append(f.name);
                    if (f.@default != null)
                    {
                        b.Append(" = ").Append(f.@default); 
                    }
                }, b => b.Append(", "));
                builder.Append(")").AppendLine();

                using (new BracketsBlock(builder))
                {
                    foreach (var f in fields)
                    {
                        builder.AppendIdent().Append("_").Append(f.name).Append(" = ").Append(f.name).Append(";")
                            .AppendLine();
                    }
                }
            }
        }

        return builder.ToString();
    }
    
    public static string Enum(string name, string[] members)
    {
        return Enum(name, members.Select<string, (string name, int? value)>(m => (m, null)).ToArray());
    }
    
    public static string Enum(string name, (string name, int? value)[] members)
    {
        var builder = new CodeBuilder.CodeBuilder();

        builder.AppendLineWithIdent("/// <auto-generated />");
        builder.AppendLine();
        
        using (new NamespaceBlock(builder, "EnumExt"))
        {
            builder.AppendIdent().Append("internal enum ").Append(name).AppendLine();

            using (new BracketsBlock(builder))
            {
                foreach (var m in members)
                {
                    builder.AppendIdent().Append(m.name);
                    if (m.value != null)
                    {
                        builder.Append(" = ").Append(m.value.ToString());    
                    }
                    builder.Append(",").AppendLine();
                }
            }
        }

        return builder.ToString();
    }

    public static string AutoGenerated()
    {
        var builder = new CodeBuilder.CodeBuilder();
        builder.AppendLineWithIdent("/// <auto-generated />");
        builder.AppendLine();
        return builder.ToString();
    }

    public static string GeneratedEnumByAttributeSummary(string attributeName, string enumName)
    {
        var builder = new CodeBuilder.CodeBuilder();
        
        builder.AppendLineWithIdent("/// <summary>");
        builder.AppendIdent().Append("/// Generated by <see cref=\"EnumExt.").Append(attributeName)
            .Append("\"/> for <see cref=\"").Append(enumName).Append("\"/> enum.").AppendLine();
        builder.AppendLineWithIdent("/// </summary>");

        return builder.ToString();
    }
}