//HintName: Role_JsonArrayConverter_Name.g.cs
/// <auto-generated />

using System.Text.Json;
using System.Text.Json.Serialization;

/// <summary>
/// Generated by <see cref="EnumExt.JsonArrayConverterAttribute"/> for <see cref="Role"/> enum.
/// </summary>
public class RoleArrayJsonConverterName : JsonConverter<Role[]>
{
    public override Role[] Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var list = new List<Role>();
        if (reader.TokenType != JsonTokenType.StartArray)
        {
            return list.ToArray();
        }
        while (reader.Read())
        {
            if (reader.TokenType == JsonTokenType.EndArray)
            {
                break;
            }
            list.Add(RoleExt.FromString(reader.GetString() ?? ""));
        }
        return list.ToArray();
    }

    public override void Write(Utf8JsonWriter writer, Role[] values, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        foreach (var value in values)
        {
            writer.WriteStringValue(value.Name());
        }
        writer.WriteEndArray();
    }
}
