//HintName: Permissions_Extensions.g.cs
/// <auto-generated />

/// <summary>
/// Generated by <see cref="EnumExt.EnumExtensionsAttribute"/> for <see cref="Permissions"/> enum.
/// </summary>
public static partial class PermissionsExt
{
    public const string EnumName = "Permissions";
    public const string SnakeCaseEnumName = "permissions";

    public static Permissions[] Values => new[]
    {
        Permissions.None,
        Permissions.Read,
        Permissions.Write,
        Permissions.Execute,
    };

    public static string[] StringValues => new[]
    {
        "None",
        "Read",
        "Write",
        "Execute",
    };

    public static int Value(this Permissions self) => (int) self;

    public static string Name(this Permissions self)
    {
        switch (self)
        {
            case Permissions.None: return "None";
            case Permissions.Read: return "Read";
            case Permissions.Write: return "Write";
            case Permissions.Execute: return "Execute";
            default: throw new System.ArgumentOutOfRangeException(nameof(self), self, null);
        }
    }

    public static string SnakeCaseName(this Permissions self)
    {
        switch (self)
        {
            case Permissions.None: return "none";
            case Permissions.Read: return "read";
            case Permissions.Write: return "write";
            case Permissions.Execute: return "execute";
            default: throw new System.ArgumentOutOfRangeException(nameof(self), self, null);
        }
    }

    public static Permissions FromString(string value)
    {
        switch (value)
        {
            case "None": return Permissions.None;
            case "Read": return Permissions.Read;
            case "Write": return Permissions.Write;
            case "Execute": return Permissions.Execute;
            default: throw new System.ArgumentOutOfRangeException(nameof(value), value, null);
        }
    }

    public static Permissions FromSnakeCaseString(string value)
    {
        switch (value)
        {
            case "none": return Permissions.None;
            case "read": return Permissions.Read;
            case "write": return Permissions.Write;
            case "execute": return Permissions.Execute;
            default: throw new System.ArgumentOutOfRangeException(nameof(value), value, null);
        }
    }

    public static Permissions FromValue(int value)
    {
        switch (value)
        {
            case 0: return Permissions.None;
            case 0: return Permissions.Read;
            case 0: return Permissions.Write;
            case 0: return Permissions.Execute;
            default: throw new System.ArgumentOutOfRangeException(nameof(value), value, null);
        }
    }

    public static Permissions FromStringValue(string value)
    {
        switch (value)
        {
            case "0": return Permissions.None;
            case "0": return Permissions.Read;
            case "0": return Permissions.Write;
            case "0": return Permissions.Execute;
            default: throw new System.ArgumentOutOfRangeException(nameof(value), value, null);
        }
    }

    public static void Fold(this Permissions self, System.Action onNone = null, System.Action onRead = null, System.Action onWrite = null, System.Action onExecute = null)
    {
        switch (self)
        {
            case Permissions.None: onNone?.Invoke(); return;
            case Permissions.Read: onRead?.Invoke(); return;
            case Permissions.Write: onWrite?.Invoke(); return;
            case Permissions.Execute: onExecute?.Invoke(); return;
            default: throw new System.ArgumentOutOfRangeException(nameof(self), self, null);
        }
    }

    public static T Fold<T>(this Permissions self, System.Func<T> onNone, System.Func<T> onRead, System.Func<T> onWrite, System.Func<T> onExecute)
    {
        switch (self)
        {
            case Permissions.None: return onNone.Invoke();
            case Permissions.Read: return onRead.Invoke();
            case Permissions.Write: return onWrite.Invoke();
            case Permissions.Execute: return onExecute.Invoke();
            default: throw new System.ArgumentOutOfRangeException(nameof(self), self, null);
        }
    }

    public static T Fold<T>(this Permissions self, T onNone, T onRead, T onWrite, T onExecute)
    {
        switch (self)
        {
            case Permissions.None: return onNone;
            case Permissions.Read: return onRead;
            case Permissions.Write: return onWrite;
            case Permissions.Execute: return onExecute;
            default: throw new System.ArgumentOutOfRangeException(nameof(self), self, null);
        }
    }
}
