//HintName: Status_Extensions.g.cs
/// <auto-generated />

/// <summary>
/// Generated by <see cref="EnumExt.EnumExtensionsAttribute"/> for <see cref="Status"/> enum.
/// </summary>
public static partial class StatusExt
{
    public const string EnumName = "Status";
    public const string SnakeCaseEnumName = "status";

    public static Status[] Values => new[]
    {
        Status.Pending,
        Status.Active,
        Status.Done,
    };

    public static string[] StringValues => new[]
    {
        "Pending",
        "Active",
        "Done",
    };

    public static int Value(this Status self) => (int) self;

    public static string Name(this Status self)
    {
        switch (self)
        {
            case Status.Pending: return "Pending";
            case Status.Active: return "Active";
            case Status.Done: return "Done";
            default: throw new System.ArgumentOutOfRangeException(nameof(self), self, null);
        }
    }

    public static string SnakeCaseName(this Status self)
    {
        switch (self)
        {
            case Status.Pending: return "pending";
            case Status.Active: return "active";
            case Status.Done: return "done";
            default: throw new System.ArgumentOutOfRangeException(nameof(self), self, null);
        }
    }

    public static Status FromString(string value)
    {
        switch (value)
        {
            case "Pending": return Status.Pending;
            case "Active": return Status.Active;
            case "Done": return Status.Done;
            default: throw new System.ArgumentOutOfRangeException(nameof(value), value, null);
        }
    }

    public static Status FromSnakeCaseString(string value)
    {
        switch (value)
        {
            case "pending": return Status.Pending;
            case "active": return Status.Active;
            case "done": return Status.Done;
            default: throw new System.ArgumentOutOfRangeException(nameof(value), value, null);
        }
    }

    public static Status FromValue(int value)
    {
        switch (value)
        {
            case 0: return Status.Pending;
            case 1: return Status.Active;
            case 2: return Status.Done;
            default: throw new System.ArgumentOutOfRangeException(nameof(value), value, null);
        }
    }

    public static Status FromStringValue(string value)
    {
        switch (value)
        {
            case "0": return Status.Pending;
            case "1": return Status.Active;
            case "2": return Status.Done;
            default: throw new System.ArgumentOutOfRangeException(nameof(value), value, null);
        }
    }

    public static void Fold(this Status self, System.Action onPending = null, System.Action onActive = null, System.Action onDone = null)
    {
        switch (self)
        {
            case Status.Pending: onPending?.Invoke(); return;
            case Status.Active: onActive?.Invoke(); return;
            case Status.Done: onDone?.Invoke(); return;
            default: throw new System.ArgumentOutOfRangeException(nameof(self), self, null);
        }
    }

    public static T Fold<T>(this Status self, System.Func<T> onPending, System.Func<T> onActive, System.Func<T> onDone)
    {
        switch (self)
        {
            case Status.Pending: return onPending.Invoke();
            case Status.Active: return onActive.Invoke();
            case Status.Done: return onDone.Invoke();
            default: throw new System.ArgumentOutOfRangeException(nameof(self), self, null);
        }
    }

    public static T Fold<T>(this Status self, T onPending, T onActive, T onDone)
    {
        switch (self)
        {
            case Status.Pending: return onPending;
            case Status.Active: return onActive;
            case Status.Done: return onDone;
            default: throw new System.ArgumentOutOfRangeException(nameof(self), self, null);
        }
    }
}
